export default [
  { name: "Afghanistan", src: "afghanistan", locale: ["ps-AF"] },
  { name: "Albania", src: "albania", locale: ["sq"] },
  { name: "Algeria", src: "algeria", locale: ["ar-DZ"] },
  { name: "Andorra", src: "andorra", locale: ["ca-AD"] },
  { name: "Angola", src: "angola", locale: ["pt-AO"] },
  {
    name: "Antigua and Barbuda",
    src: "antigua-and-barbuda",
    locale: ["en-AG"]
  },
  {
    name: "Argentina",
    src: "argentina",
    locale: ["es-AR"]
  },
  { name: ["Armenian", "Armenia"], src: "armenia", locale: ["hy-AM"] },
  { name: "Aruba", src: "aruba", locale: ["nl-AW"] },
  {
    name: "Australia",
    src: "australia",
    locale: ["en-AU"]
  },
  { name: "Austria", src: "austria", locale: ["de-AT"] },
  { name: "Azerbaijan", src: "azerbaijan", locale: ["az-AZ"] },
  { name: "Bahamas", src: "bahamas", locale: ["en-BS"] },
  { name: "Bahrain", src: "bahrain", locale: ["ar-BH"] },
  { name: "Bangladesh", src: "bangladesh", locale: ["bn-BD"] },
  { name: "Barbados", src: "barbados", locale: ["en-BB"] },
  { name: "Belarus", src: "belarus", locale: ["ru-BY"] },
  { name: "Belgium", src: "belgium", locale: ["nl-BE", "fr-BE"] },
  { name: "Belize", src: "belize", locale: ["en-BZ"] },
  { name: "Benin", src: "benin", locale: ["fr-BJ"] },
  { name: "Bhutan", src: "bhutan", locale: ["dz-BT"] },
  { name: "Bolivia", src: "bolivia", locale: ["es-BO"] },
  { name: "Bonaire", src: "bonaire", locale: ["bq-BO"] },
  {
    name: "Bosnia and Herzegovina",
    src: "bosnia-and-herzegovina",
    locale: ["sr-BA"]
  },
  { name: "Botswana", src: "botswana", locale: ["en-BW"] },
  { name: "Brazil", src: "brazil", locale: ["pt-BR"] },
  { name: "Brunei", src: "brunei", locale: ["ms-BN"] },
  {
    name: ["Bulgaria", "Republic of Bulgaria"],
    src: "bulgaria",
    locale: ["bg-BG"]
  },
  { name: "Burkina Faso", src: "burkina-faso", locale: ["fr-BF"] },
  { name: "Burundi", src: "burundi", locale: ["fr-BI"] },
  { name: "Cambodia", src: "cambodia", locale: ["km-KH"] },
  { name: "Cameroon", src: "cameroon", locale: ["fr-CM"] },
  { name: "Canada", src: "canada", locale: ["en", "en-CA", "fr-CA"] },
  { name: "Cape Verde", src: "cape-verde", locale: ["pt-CV"] },
  {
    name: "Central African Republic",
    src: "central-african-republic",
    locale: ["sg-CF"]
  },
  { name: "Chile", src: "chile", locale: ["es-CL"] },
  {
    name: ["People's Republic of China", "China"],
    src: "china",
    locale: ["zh-CN"]
  },
  { name: "Colombia", src: "colombia", locale: ["es-CO"] },
  { name: "Comoros", src: "comoros", locale: ["ar-KM"] },
  {
    name: "Democratic Republic of the Congo",
    src: "congo-democratic-republic",
    locale: ["fr-CO"]
  },
  {
    name: "Republic of the Congo",
    src: "congo-republic",
    locale: ["ln-CD"]
  },
  { name: "Costa Rica", src: "costa-rica", locale: ["es-CR"] },
  {
    name: ["Ivory Coast", "Côte d'Ivoire", "Republic of Côte d'Ivoire"],
    src: "cote-d-ivoire",
    locale: ["fr-CI"]
  },
  { name: "Coatia", src: "croatia", locale: ["hr"] },
  { name: "Cuba", src: "cuba", locale: ["es-CU"] },
  { name: "Curacao", src: "curacao", locale: ["nl-CW"] },
  { name: "Cyprus", src: "cyprus", locale: ["el-CY"] },
  {
    name: ["Czech Republic", "Czechia", "Czechoslovak Socialist Republic"],
    src: "czechia",
    locale: ["cs-CZ"]
  },
  { name: "Denmark", src: "denmark", locale: ["da-DK"] },
  { name: "Djibouti", src: "djibouti", locale: ["fr-DJ"] },
  { name: "Dominica", src: "dominica", locale: ["en-DM"] },
  {
    name: "Dominican Republic",
    src: "dominican-republic",
    locale: ["es-DO"]
  },
  { name: "East Timor", src: "east-timor", locale: ["pt-TL"] },
  { name: "Ecuador", src: "ecuador", locale: ["es-EC"] },
  { name: "Egypt", src: "egypt", locale: ["ar-EG"] },
  { name: "England", src: "england", locale: ["en-EN"] },
  {
    name: "Equatorial Guinea",
    src: "equatorial-guinea",
    locale: ["es-GQ"]
  },
  { name: "Eritrea", src: "eritrea", locale: ["en-ER"] },
  { name: "Estonia", src: "estonia", locale: ["et-EE"] },
  { name: "Ethiopia", src: "ethiopia", locale: ["am-ET", "om-ET"] },
  { name: "Faroe Islands", src: "faroe-islands", locale: ["fo-FO"] },
  { name: "Fiji", src: "fiji", locale: ["en-FJ"] },
  { name: "Finland", src: "finland", locale: ["fi-FI"] },
  { name: "France", src: "france", locale: ["fr-FR"] },
  { name: "Gabon", src: "gabon", locale: ["fr-GA"] },
  { name: "Gambia", src: "gambia", locale: ["fr-GA"] },
  { name: "Georgia", src: "georgia", locale: ["os-GE"] },
  { name: "Germany", src: "germany", locale: ["de-DE"] },
  { name: "Ghana", src: "ghana", locale: ["ak-GH", "en-GH"] },
  { name: "Greece", src: "greece", locale: ["el-GR"] },
  { name: "Greenland", src: "greenland", locale: ["kl-GL"] },
  { name: "Guadeloupe", src: "guadeloupe", locale: [] },
  { name: "Guam", src: "guam", locale: ["en-GU"] },
  { name: "Guatemala", src: "guatemala", locale: ["es-GT"] },
  { name: "Guinea Bissau", src: "guinea-bissau", locale: ["pt-GW"] },
  { name: "Guinea", src: "guinea", locale: ["ff-GN", "fr-GN"] },
  { name: "Guyana", src: "guyana", locale: ["en-GY"] },
  { name: "Haiti", src: "haiti", locale: ["ht-HT", "fr-HT"] },
  { name: "Honduras", src: "honduras", locale: ["es-HN"] },
  {
    name: ["British Hong Kong", "Hong Kong"],
    src: "hongkong",
    locale: ["zh-HK"]
  },
  { name: "Hungary", src: "hungary", locale: ["hu-HU"] },
  { name: "Iceland", src: "iceland", locale: ["is-IS"] },
  { name: "India", src: "india", locale: ["en-IN", "hi-IN"] },
  { name: "Indonesia", src: "indonesia", locale: ["in-ID"] },
  { name: "Iran", src: "iran", locale: ["fa-IR"] },
  { name: "Iraq", src: "iraq", locale: ["ar-IQ"] },
  { name: "Ireland", src: "ireland", locale: ["en-IE", "ga-IE"] },
  { name: "Israel", src: "israel", locale: ["iw-IL"] },
  { name: "Italy", src: "italy", locale: ["it-IT"] },
  { name: "Jamaica", src: "jamaica", locale: ["en-JM"] },
  { name: "Japan", src: "japan", locale: ["ja-JP"] },
  { name: "Jordan", src: "jordan", locale: ["ar-JO"] },
  { name: "Kazakhstan", src: "kazakhstan", locale: ["kk-KZ"] },
  { name: "Kenya", src: "kenya", locale: ["en-KE"] },
  { name: "Kiribati", src: "kiribati", locale: ["en-KI"] },
  { name: "Kosovo", src: "kosovo", locale: ["sq-XK"] },
  { name: "Kuwait", src: "kuwait", locale: ["ar-KW"] },
  { name: "Kyrgyzstan", src: "kyrgyzstan", locale: ["ky-KG", "ru-KG"] },
  { name: "Laos", src: "laos", locale: ["lo-LA"] },
  { name: "Latvia", src: "latvia", locale: ["lv-LV"] },
  { name: "Lebanon", src: "lebanon", locale: ["ar-LB"] },
  { name: "Lesotho", src: "lesotho", locale: ["en-LS"] },
  { name: "Liberia", src: "liberia", locale: ["en-LR"] },
  { name: "Libya", src: "libya", locale: ["ar-LY"] },
  { name: "Liechtenstein", src: "liechtenstein", locale: ["de-LI"] },
  { name: "Lithuania", src: "lithuania", locale: ["lt-LT"] },
  { name: "Luxembourg", src: "luxembourg", locale: ["fr-LU", "de-LU"] },
  { name: "Macau", src: "macau", locale: ["en-MO"] },
  { name: "Macedonia", src: "macedonia", locale: ["mk-MK", "sq-MK"] },
  { name: "Madagascar", src: "madagascar", locale: ["mg-MG", "fr-MG"] },
  { name: "Malawi", src: "malawi", locale: ["en-MW"] },
  { name: "Malaysia", src: "malaysia", locale: ["ms-MY"] },
  { name: "Maldives", src: "maldives", locale: ["dv-MV"] },
  { name: "Mali", src: "mali", locale: ["bm-ML"] },
  { name: "Malta", src: "malta", locale: ["en-MT", "mt-MT"] },
  {
    name: "Marshall Islands",
    src: "marshall-islands",
    locale: ["en-MH"]
  },
  { name: "Mauritania", src: "mauritania", locale: ["fr-MR", "ar-MR"] },
  { name: "Mexico", src: "mexico", locale: ["es-MX"] },
  { name: "Micronesia", src: "micronesia", locale: ["en-FM"] },
  { name: "Moldova", src: "moldova", locale: ["ro-MD", "ru-MD"] },
  { name: "Monaco", src: "monaco", locale: ["fr-MC"] },
  { name: "Mongolia", src: "mongolia", locale: ["mn-MN"] },
  { name: "Montenegro", src: "montenegro", locale: ["sr-ME"] },
  { name: "Morocco", src: "morocco", locale: ["ar-MA"] },
  { name: "Mozambique", src: "mozambique", locale: ["pt-MZ"] },
  { name: ["Burma", "Myanmar"], src: "myanmar", locale: ["my-MM"] },
  { name: "Namibia", src: "namibia", locale: ["en-NA"] },
  { name: "Nauru", src: "nauru", locale: ["en-NR"] },
  { name: "Nepal", src: "nepal", locale: ["ne-NP"] },
  {
    name: ["Kingdom of the Netherlands", "Netherlands"],
    src: "netherlands",
    locale: ["nl-NL"]
  },
  { name: "New Caledonia", src: "new-caledonia", locale: ["fr-NC"] },
  { name: "New Zealand", src: "new-zealand", locale: ["en-NZ"] },
  { name: "Nicaragua", src: "nicaragua", locale: ["es-NI"] },
  { name: "Niger", src: "niger", locale: ["dje-NE"] },
  { name: "Nigeria", src: "nigeria", locale: ["ig-NG"] },
  { name: "Niue", src: "niue", locale: ["en-NU"] },
  { name: "North Korea", src: "north-korea", locale: ["ko-KP"] },
  {
    name: "Northern Ireland",
    src: "northern-ireland",
    locale: ["en-IE"]
  },
  { name: "Norway", src: "norway", locale: ["no-NO"] },
  { name: "Oman", src: "oman", locale: ["ar-OM"] },
  { name: "Pakistan", src: "pakistan", locale: ["en-PK", "ur-PK"] },
  { name: "Palau", src: "palau", locale: ["en-PW"] },
  { name: "Plestina", src: "palestina", locale: ["ar-PS"] },
  { name: "Panama", src: "panama", locale: ["es-PA"] },
  { name: "Paraguay", src: "paraguay", locale: ["es-PY"] },
  { name: "Peru", src: "peru", locale: ["es-PE"] },
  { name: "Philippines", src: "philippines", locale: ["en-PH"] },
  { name: "Poland", src: "poland", locale: ["po-PL"] },
  { name: "Portugal", src: "portugal", locale: ["pt-PT"] },
  { name: "Puerto Rico", src: "puerto-rico", locale: ["es-PR"] },
  { name: "Qatar", src: "qatar", locale: ["ar-QA"] },
  { name: "Romania", src: "romania", locale: ["ro-RO"] },
  { name: ["Soviet Union", "Russia"], src: "russia", locale: ["ru-RU"] },
  { name: "Rwanda", src: "rwanda", locale: ["rw-RW"] },
  { name: "Saba", src: "saba", locale: ["bq-SA"] },
  { name: "Saint Eustatius", src: "saint-eustatius", locale: ["bq-SE"] },
  { name: "Saint Lucia", src: "saint-lucia", locale: ["en-LC"] },
  { name: "Saint Martin", src: "saint-martin", locale: ["fr-MF"] },
  {
    name: "Saint Vincent and the Grenadines",
    src: "saint-vincent-and-the-grenadines",
    locale: ["en-VC"]
  },
  { name: "Samoa", src: "samoa", locale: ["en-AS"] },
  { name: "San Marino", src: "san-marino", locale: ["it-SM"] },
  {
    name: "Sao Tome and Principe",
    src: "sao-tome-and-principe",
    locale: ["pt-ST"]
  },
  { name: "Saudi Arabia", src: "saudi-arabia", locale: ["ar-SA"] },
  { name: "Scotland", src: "scotland", locale: ["gd-GB"] },
  { name: "Senegal", src: "senegal", locale: ["fr-SN"] },
  {
    name: ["Serbia", "Serbia and Montenegro", "Yugoslavia"],
    src: "serbia",
    locale: ["sr-RS"]
  },
  { name: "Seychelles", src: "seychelles", locale: ["en-SC"] },
  { name: "Sierra Leone", src: "sierra-leone", locale: ["en-SL"] },
  { name: "Singapore", src: "singapore", locale: ["zh-SG", "en-SG"] },
  { name: "Slovakia", src: "slovakia", locale: ["sk-SK"] },
  { name: "Slovenia", src: "slovenia", locale: ["sl-SI"] },
  { name: "Solomon Islands", src: "solomon-islands", locale: ["en-SB"] },
  { name: "Somalia", src: "somalia", locale: ["so-SO"] },
  { name: "South Africa", src: "south-africa", locale: ["en-ZA"] },
  { name: "South Korea", src: "south-korea", locale: ["ko-KR"] },
  { name: "Spain", src: "spain", locale: ["es-ES"] },
  { name: "Sri Lanka", src: "sri-lanka", locale: ["si-LK", "ta-LK"] },
  { name: "Sudan", src: "sudan", locale: ["en-SD"] },
  { name: "Suriname", src: "suriname", locale: ["nl-SR"] },
  { name: "Swaziland", src: "swaziland", locale: ["en-SZ"] },
  { name: "Sweden", src: "sweden", locale: ["sv-SE"] },
  {
    name: "Switzerland",
    src: "switzerland",
    locale: ["fr-CH", "de-CH", "it-CH"]
  },
  { name: "Syria", src: "syria", locale: ["ar-SY"] },
  { name: "Taiwan", src: "taiwan", locale: ["zh-TW"] },
  { name: "Tajikistan", src: "tajikistan", locale: ["tg-TJ"] },
  { name: "Tanzania", src: "tanzania", locale: ["en-TZ", "sw-TZ"] },
  { name: "Thailand", src: "thailand", locale: ["th-TH"] },
  { name: "Togo", src: "togo", locale: ["ee-TG", "fr-TG"] },
  { name: "Tonga", src: "tonga", locale: ["to-TO"] },
  {
    name: "Trinidad and Tobago",
    src: "trinidad-and-tobago",
    locale: ["en-TT"]
  },
  { name: "Tunisia", src: "tunisia", locale: ["ar-TN"] },
  { name: "Turkey", src: "turkey", locale: ["tr-TR"] },
  { name: "Turkmenistan", src: "turkmenistan", locale: ["tk-TM"] },
  { name: "Tuvalu", src: "tuvalu", locale: ["en-TV"] },
  { name: "Uganda", src: "uganda", locale: ["lg-UG"] },
  { name: "Ukraine", src: "ukraine", locale: ["uk-UA"] },
  {
    name: "United Arab Emirates",
    src: "united-arab-emirates",
    locale: ["ar-AE"]
  },
  {
    name: ["United Kingdom", "UK"],
    src: "united-kingdom",
    locale: ["en-GB"]
  },
  {
    name: ["United States of America", "US", "USA"],
    src: "united-states-of-america",
    locale: ["en-US", "es-US"]
  },
  { name: "Uruguay", src: "uruguay", locale: ["es-UY"] },
  { name: "Uzbekistan", src: "uzbekistan", locale: ["uz-UZ"] },
  { name: "Vanuatu", src: "vanuatu", locale: ["en-VU", "fr-VU"] },
  { name: "Vatican City", src: "vatican-city", locale: ["it-VA"] },
  { name: "Venezuela", src: "venezuela", locale: ["es-VE"] },
  { name: "Vietnam", src: "vietnam", locale: ["vi-VN"] },
  { name: "Wales", src: "wales", locale: ["cy-GB"] },
  { name: "Yemen", src: "yemen", locale: ["ar-YE"] },
  { name: "Zambia", src: "zambia", locale: ["en-ZM", "bem-ZM"] },
  { name: "Zimbabwe", src: "zimbabwe", locale: ["en-ZW", "sn-ZW"] }
];
